apiVersion: v2
name: karpor
version: 0.7.6
type: application
appVersion: 0.6.3-alpha.4
description: A modern kubernetes visualization tool (Karpor).
home: https://github.com/KusionStack/karpor
icon: https://kusionstack.io/karpor/assets/logo/logo.svg
maintainers:
  - name: kusionstack
    email: kusionstack@gmail.com
    url: https://kusionstack.io/karpor
sources:
  - https://github.com/KusionStack/charts/tree/master/charts/karpor
  - https://github.com/KusionStack/karpor
keywords:
  - KusionStack
  - karpor
